title: adityakumar25
description: Content Creator
theme: jekyll-theme-minimal
[Why LLMs Charge Per Token: The Compute Behind a Single Query](https://github.com/adityakumar25/adityakumar25.github.io/blob/main/Compute%20Cost%20of%20an%20LLM%20Query.docx)
